/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_Stock;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;


public class furnitureStock extends javax.swing.JFrame {

    Connection con = null; // change /direct interface connection
    PreparedStatement pst = null;// chanege / direct interface connection
    ResultSet rs = null;
    String model=null;
    String category=null;
    String s=null;
    String y=null;
    /**
     * Creates new form furniture_stock
     */
    public furnitureStock() {
        initComponents();
        
       
        con = DBconnect.connect(); 
        searchbkbox.setVisible(false);
        
        //tableload
        tableload();
        
        fillcombo();
        
    }
    public void setMe(String s){
        y=s;
    }
    public boolean chkExist(){
        boolean res = false;
        //System.out.println("*********newphase***********");
        try{
            s="SELECT * FROM furniturestock";
            pst = con.prepareStatement(s);
            rs = pst.executeQuery();
                while(rs.next()){
                    String s1 = rs.getString("product");
                    String s2 = rs.getString("model");
                    String s3 = rs.getString("quantity");
                    System.out.println(category+" "+model);
                        if(new String(category).equals(s1) && new String(model).equals(s2)){
                            //System.out.println("true "+s1+" "+s2);
                            setMe(s3);
                            res = true;
                  
                        }
                        else{
                            //System.out.println("false "+s1+" "+s2);
                            res = false;
                          
                        }
                }
        }
        catch(Exception e){
            System.out.println(e);
        }
         return res;
    }
    
    public void tableload() 
    {
        try{
        String sql ="SELECT product,model,quantity FROM furniturestock";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       
        }
        catch (Exception e){
            
            System.out.print(e);
        }
    }

    
    public void reset()
    {
       // String s=null;
//      categorybox.setSelectedItem("");
//      //modelbox.setSelectedItem("Select model");
      Quntbox.setText("");
    
    
    }
    
    public void fillcombo()
    {
        
        String sql = "select distinct product from furniture";
        try
        {
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            //categorybox.removeAllItems();
            //cmbModel.removeAllItems();
            
            while(rs.next())
            {
                categorybox.addItem(rs.getString("product"));
                
            }
        }
        catch(Exception e)
        {
            System.out.println();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        searchc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        searchbkbox = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modelbox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        categorybox = new javax.swing.JComboBox();
        searchm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Quntbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Furniture Category");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter category");

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        searchbkbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchbkbox.setText("<<");
        searchbkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbkboxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Model", "Quantity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        modelbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        modelbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modelboxItemStateChanged(evt);
            }
        });
        modelbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter Model");

        categorybox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoryboxItemStateChanged(evt);
            }
        });
        categorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Model");

        Quntbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuntboxActionPerformed(evt);
            }
        });
        Quntbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuntboxKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Furniture Stock");

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton6)
                .addGap(171, 171, 171)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(categorybox, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(modelbox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(Quntbox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(searchc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(searchm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(searchbkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(categorybox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(modelbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(Quntbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(searchm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(19, 19, 19)
                .addComponent(searchbkbox)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String category = searchc.getText();
        String model = searchm.getText();

        // check the text fileds are empty or not
        if(model.isEmpty() || category.isEmpty()){

            JOptionPane.showMessageDialog(null,"Please Fill All Text Fields");
        }
        else
        {

            String sql = "Select product, model, quantity from furniturestock where product LIKE '%"+ category +"%' and model LIKE '%"+ model +"%'";

            try {

                pst = con .prepareStatement(sql);
                rs= pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }
            catch (Exception e)
            {
                System.out.println(e);
            }

            searchbkbox.setVisible(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String category = categorybox.getSelectedItem().toString();
        String model = modelbox.getSelectedItem().toString();
        String Quantity = Quntbox.getText();

        if( Quantity.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please  Select  What Do You Want To Delete");
        }

        else{
            int x = JOptionPane.showConfirmDialog(null, "Do You Want To Delete This");

            if (x==0)
            {
                String sql = "DELETE from furniturestock where product='"+ category +"' and model='"+ model +"' and quantity='"+ Quantity +"'";

                try{
                    pst = con .prepareStatement(sql);
                    pst.execute();

                    tableload();

                    reset();

                }
                catch (Exception e)
                {
                    System.out.print(e);
                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        reset();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        category = categorybox.getSelectedItem().toString();
        model  = modelbox.getSelectedItem().toString();
        String quantity = Quntbox.getText();

        if(chkExist()){
            int newQty= Integer.parseInt(y)+Integer.parseInt(quantity);
            String Qty = Integer.toString(newQty);
            //System.out.println(newQty);
            String sql="UPDATE furniturestock SET quantity = '"+ Qty +"' WHERE product = '"+ category +"' and model = '"+ model +"'";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                tableload();
                reset();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else{

            if(quantity.isEmpty())// check qnty textfield empty or  not
            {
                JOptionPane.showMessageDialog(null,"Please  Fill  All  Fileds");
            }
            else {
                try{
                    String q = "INSERT INTO furniturestock (product,model,quantity) values ('"+ category +"', '"+ model +"', '"+ quantity +"')";
                    pst = con.prepareStatement(q);
                    pst.execute();
                    tableload();
                    reset();
                }
                catch (Exception e){
                    System.out.println(e);
                }

    }//GEN-LAST:event_jButton1ActionPerformed
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String product = categorybox.getSelectedItem().toString();
        String model = modelbox.getSelectedItem().toString();
        String quantity = Quntbox.getText();

        if (quantity.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please  Select  What Do You Want To Update");
        }

        else  {
            int x = JOptionPane.showConfirmDialog(null," Do You Want To Really Update");

            if(x==0)
            {
                String sql ="UPDATE furniturestock SET quantity = '"+ quantity +"' WHERE product = '"+ product +"' and model = '"+ model +"'";

                try{
                    pst = con.prepareStatement(sql);
                    pst.execute();

                    tableload();
                }
                catch(Exception e)

                {

                    System.out.print(e);
                }
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchbkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbkboxActionPerformed
        // TODO add your handling code here:
        tableload();
        this.searchbkbox.setVisible(false);
    }//GEN-LAST:event_searchbkboxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int raw = jTable1.getSelectedRow();

        String category = jTable1.getValueAt(raw, 0).toString();
        String model =  jTable1.getValueAt(raw, 1).toString();
        String quantity =  jTable1.getValueAt(raw, 2).toString();

        categorybox.setSelectedItem(category);
        modelbox.setSelectedItem(model);
        Quntbox.setText(quantity);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void modelboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modelboxItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_modelboxItemStateChanged

    private void modelboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelboxActionPerformed

    private void categoryboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoryboxItemStateChanged
        String s = categorybox.getSelectedItem().toString();
        String sql = "SELECT model from furniture where product = '"+ s +"' ";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            modelbox.removeAllItems();
            while(rs.next())
            {
                modelbox.addItem(rs.getString("model"));
            }

        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryboxItemStateChanged

    private void categoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryboxActionPerformed

    private void QuntboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuntboxKeyReleased
        String quantity =Quntbox.getText();

        for(int i=0;i<quantity.length();i++)
        {
            char c = quantity.charAt(i);
            if(Character.isDigit(c))
            {

            }

            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null,"This Field can not have Letters","Error",0);
                Quntbox.setText("");

                break;
            }

            else
            {
                JOptionPane.showMessageDialog(null,"This Field can not have Special Charactor","Error",0);
                Quntbox.setText("");

                break;
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_QuntboxKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mainStock x = new mainStock();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void QuntboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuntboxActionPerformed
        // TODO add your handling code here:
        
        String faccos =Quntbox.getText();
         
        for(int i =0; i<faccos.length(); i++){
        
        char c = faccos.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            Quntbox.setText(" ");
 
            break;
        }
        }
        
    }//GEN-LAST:event_QuntboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(furnitureStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(furnitureStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(furnitureStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(furnitureStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new furnitureStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Quntbox;
    private javax.swing.JComboBox categorybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox modelbox;
    private javax.swing.JButton searchbkbox;
    private javax.swing.JTextField searchc;
    private javax.swing.JTextField searchm;
    // End of variables declaration//GEN-END:variables
}
