/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_Employee;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;


public class salary extends javax.swing.JFrame {
   
     Connection conn = null;
    PreparedStatement pstt = null;
    ResultSet rss = null;
    PreparedStatement pstt1 = null;
    ResultSet rss1 = null;
    double etfAmt,epfAmt,fsalary,ot;
    double hrs,sala,cetf,cepf,rate;
    
    public salary() {
        initComponents();
        conn = DBconnect.connect();
        tableloads();
        comboload();
      
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
    public double calcOt(double hrs,double rate){
        return hrs*rate;
    }
    public double calcSal(double ot,double epfAmt, double salary){
        double sal = 0;
        sal = salary + ot - epfAmt;
        return sal;
    }
    public double calcEtf(double etf,double salary){
        return salary*etf/100;
    }
    public double calcEpf(double epf,double salary){
        return salary*epf/100;   
    }
    public void tableloads(){
    try{
    
    String sqll = "SELECT empId , BasicSal , OverTime , OtRate , EtfRate , EpfRate , etfAmt , epfAmt FROM salary";
    pstt = conn.prepareStatement(sqll);
    rss = pstt.executeQuery();
    //rss.getString(1);
    jTable1.setModel(DbUtils.resultSetToTableModel(rss));
    
    }catch (Exception e){
    
    System.out.println(e);
    }
    
    
    }
    
    public void comboload(){
        try{     
                 String sql="SELECT empId FROM employee ";
                 pstt = conn.prepareStatement(sql);
                 rss = pstt.executeQuery();
                 cmbEmpId.removeAllItems();
                 cmbEmpId.addItem("Select");    
                 while(rss.next()){
                     String id=rss.getString(1);

                     cmbEmpId.addItem(id);
                 }


             }catch(Exception e){

             }
    }

    public void reset()
    {
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
        txtEpf.setText("");
        txtEtf.setText("");
        txtOt.setText("");
        txtOtrate.setText("");
        txtSalary.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSalary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtOt = new javax.swing.JTextField();
        txtOtrate = new javax.swing.JTextField();
        txtEtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cmbEmpId = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalaryKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Employee Salary Details");

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtOt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtKeyReleased(evt);
            }
        });

        txtOtrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtrateKeyReleased(evt);
            }
        });

        txtEtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEtfKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");

        txtEpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEpfKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Basic Salary");

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Over Time");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Basic Salary", "Over Time", "OT Rate", "ETF Rate", "EPF Rate", "ETF Amount", "EPF Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("OT Rate");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ETF Rate");

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("EPF Rate");

        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cmbEmpId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmpId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEmpIdItemStateChanged(evt);
            }
        });
        cmbEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(cmbEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(119, 119, 119)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(160, 160, 160)
                        .addComponent(txtOtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(127, 127, 127)
                        .addComponent(txtOt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(155, 155, 155)
                        .addComponent(txtEtf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(txtEpf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton5))
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtOtrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtEtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = cmbEmpId.getSelectedItem().toString();
        String salary = txtSalary.getText();
        //String loan = txtLoan.getText();
        //String month = txtMonth.getText();
        String otime = txtOt.getText();
        String otrate = txtOtrate.getText();
        String etf = txtEtf.getText();
        String epf = txtEpf.getText();

        hrs = Double.parseDouble(otime);
        rate = Double.parseDouble(otrate);
        sala =Double.parseDouble(salary);
        cetf = Double.parseDouble(etf);
        cepf = Double.parseDouble(epf);

        //calcOt(hrs,rate);
        ot = calcOt(hrs,rate);
        etfAmt= calcEtf(cetf,sala);
        epfAmt= calcEpf(cepf,sala);
        fsalary = calcSal(ot,epfAmt,sala);

        try{
            String p ="INSERT INTO salary (empId , BasicSal , OverTime , OtRate , EtfRate , EpfRate , Fsalary ,etfAmt , epfAmt ) values ('"+ id +"' , '"+ salary +"' , '"+ otime +"' , '"+ otrate +"' , '"+ etf +"' , '"+ epf +"' , '"+ fsalary +"' , '"+ etfAmt +"' , '"+ epfAmt +"')";

            pstt = conn.prepareStatement(p);
            pstt.execute();

            tableloads();
            reset();

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        
        try{

            int r = jTable1.getSelectedRow();

            String id = jTable1.getValueAt(r, 0).toString();
            String salary = jTable1.getValueAt(r, 1).toString();
            //String loan = jTable1.getValueAt(r, 2).toString();
            //String month = jTable1.getValueAt(r, 3).toString();
            String otime = jTable1.getValueAt(r, 2).toString();
            String otrate = jTable1.getValueAt(r, 3).toString();
            String etf = jTable1.getValueAt(r, 4).toString();
            String epf = jTable1.getValueAt(r, 5).toString();

            cmbEmpId.setSelectedItem(id);
            txtSalary.setText(salary);
            //txtLoan.setText(loan);
            //txtMonth.setText(month);
            txtOt.setText(otime);
            txtOtrate.setText(otrate);
            txtEtf.setText(etf);
            txtEpf.setText(epf);

        }catch (Exception e){

            System.out.println(e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int b = JOptionPane.showConfirmDialog(null,"Do You Want To UpDate ?");

        if (b==0){

            String id = cmbEmpId.getSelectedItem().toString();
            String salary = txtSalary.getText();
            //String loan = txtLoan.getText();
            //String month = txtMonth.getText();
            String otime =txtOt.getText();
            String otrate = txtOtrate.getText();
            String etfrate = txtEtf.getText();
            String epfrate = txtEpf.getText();
            String etf = txtEtf.getText();
            String epf = txtEpf.getText();

            hrs = Double.parseDouble(otime);
            rate = Double.parseDouble(otrate);
            sala =Double.parseDouble(salary);
            cetf = Double.parseDouble(etf);
            cepf = Double.parseDouble(epf);
            ot = calcOt(hrs,rate);
            etfAmt= calcEtf(cetf,sala);
            epfAmt= calcEpf(cepf,sala);
            fsalary = calcSal(ot,epfAmt,sala);

            String sqll = "UPDATE salary SET BasicSal = '"+ salary +"' , OverTime = '"+ otime +"' ,OtRate = '"+ otrate +"' , EtfRate = '"+ etfrate +"' , EpfRate = '"+ epfrate+"', Fsalary = '"+ fsalary +"', epfAmt = '"+ epfAmt +"', etfAmt = '"+ etfAmt +"'  WHERE empId = '"+ id +"'";

            try{
                pstt = conn.prepareStatement(sqll);
                pstt.execute();
                tableloads();
                reset();
            }
            catch (Exception e)
            {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(null,"Do You Want To Delete ?");
        if( x==0 ){
            String id = cmbEmpId.getSelectedItem().toString();

            String sqll = "DELETE FROM salary WHERE empId = '"+ id +"'";
            try{
                pstt = conn.prepareStatement(sqll);
                pstt.execute();
                tableloads();
                reset();

            }catch (Exception e){
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mainEmployees x = new mainEmployees();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyReleased
        // TODO add your handling code here:
         String x =txtSalary.getText();
         
        for(int i =0; i<x.length(); i++){
        
        char c = x.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txtSalary.setText(" ");
 
            break;
        }
        }
    }//GEN-LAST:event_txtSalaryKeyReleased

    private void txtOtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtKeyReleased
        // TODO add your handling code here:
        
         String x =txtOt.getText();
         
        for(int i =0; i<x.length(); i++){
        
        char c = x.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txtOt.setText(" ");
 
            break;
        }
        }
        
    }//GEN-LAST:event_txtOtKeyReleased

    private void txtOtrateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtrateKeyReleased
        // TODO add your handling code here:
        String x =txtOtrate.getText();
         
        for(int i =0; i<x.length(); i++){
        
        char c = x.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txtOtrate.setText(" ");
 
            break;
        }
        }
        
    }//GEN-LAST:event_txtOtrateKeyReleased

    private void txtEtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEtfKeyReleased
        // TODO add your handling code here:
        
        String x =txtEtf.getText();
         
        for(int i =0; i<x.length(); i++){
        
        char c = x.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txtEtf.setText(" ");
 
            break;
        }
        }
        
    }//GEN-LAST:event_txtEtfKeyReleased

    private void txtEpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEpfKeyReleased
        // TODO add your handling code here:

       String x =txtEpf.getText();
         
        for(int i =0; i<x.length(); i++){
        
        char c = x.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txtEpf.setText(" ");
 
            break;
        }
        } 
        
    }//GEN-LAST:event_txtEpfKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbEmpIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEmpIdItemStateChanged
//              String a = cmbEmpId.getSelectedItem().toString();
//        String quary="SELECT `empName` FROM `employee` WHERE `empId`='"+a+"' ";
//         try {
//             pstt1=conn.prepareStatement(quary);
//             rss1=pstt1.executeQuery();
//             while(rss1.next()){
//             jLabel5.setText(rss1.getString("empName"));
//             }
//            
//             
//         } catch (Exception ex) {
//             System.out.println(ex);
//         }
       
     
        
    }//GEN-LAST:event_cmbEmpIdItemStateChanged

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void cmbEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpIdActionPerformed
         
  
    }//GEN-LAST:event_cmbEmpIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbEmpId;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEpf;
    private javax.swing.JTextField txtEtf;
    private javax.swing.JTextField txtOt;
    private javax.swing.JTextField txtOtrate;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
