/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_Sales;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;


public class customers extends javax.swing.JFrame {
    Connection con = null; 
    PreparedStatement pst = null;
    ResultSet rs = null;
//    int x = 1000;
    
    /**
     * Creates new form intCustomer
     */
    public customers() {
        initComponents();
        
                //connect to DB
        con = DBconnect.connect();
        
        tableload(); 
        
    }
    
 
    
    public void reset()
    {
        tableload();
        btn_Update.setEnabled(false);
        btn_Remove.setEnabled(false);
        btn_Save.setEnabled(true);
        
        lbl_ID.setText("ID");
        txt_search.setText("");
        txt_Name.setText("");
        txt_Address.setText("");
        txt_Email.setText("");
        txt_TP.setText("");
        txtNic.setText("");
    }
    
    public void tableload()
    {
        try
        {
        String sql = "SELECT customerID,name,nic,address,email,telephone FROM customer";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        tbl_cus.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
        }
    }
    
    public boolean validator()
    {
        if (txt_Name.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Name Field is Empty ");
            return false;
        }
        else if (txt_Address.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Address Field is Empty ");
            return false;
        }
        else if (txt_TP.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Telephone Field is Empty ");
            return false;
        }
        else if (txt_TP.getText().length()!=10)
        {
            JOptionPane.showMessageDialog(null,"Enter a Valid Contact Number");
            return false;
        }
        
        
        return true;
    } 
    
//    public String increment(String s){
//        String val =s+x;
//        x++;
//        return val;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        lbl_cusRegistration = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cus = new javax.swing.JTable();
        btn_search = new javax.swing.JButton();
        lbl_cusNo = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        btn_Remove = new javax.swing.JButton();
        lbl_Name = new javax.swing.JLabel();
        txt_TP = new javax.swing.JTextField();
        lbl_searchNmae = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        lbl_Address = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        btn_Save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Address = new javax.swing.JTextArea();
        lbl_TP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.setEnabled(false);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        lbl_cusRegistration.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_cusRegistration.setText("Coustomer Registration");

        lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Email.setText("Email ");

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tbl_cus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_cus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Number", "First Name", "Address", "Email", "Telephone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cus);

        btn_search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        lbl_cusNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cusNo.setText("Coustomer ID  ");

        txt_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_Remove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Remove.setText("Remove");
        btn_Remove.setEnabled(false);
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        lbl_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Name.setText("Name  ");

        txt_TP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TPKeyReleased(evt);
            }
        });

        lbl_searchNmae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_searchNmae.setText("Name : ");

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_Address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Address.setText("Address ");

        lbl_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_Save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        txt_Address.setColumns(20);
        txt_Address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Address.setRows(5);
        jScrollPane2.setViewportView(txt_Address);

        lbl_TP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TP.setText("Telephone ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NIC");

        txtNic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(111, 111, 111)
                .addComponent(lbl_cusRegistration))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_cusNo)
                .addGap(66, 66, 66)
                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbl_searchNmae)
                .addGap(32, 32, 32)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_Name)
                .addGap(55, 55, 55)
                .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbl_Email)
                .addGap(45, 45, 45)
                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TP)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_TP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lbl_Address))
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btn_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1))
                    .addComponent(lbl_cusRegistration))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_cusNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_searchNmae))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_search))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Name)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TP)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Address)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Save)
                    .addComponent(btn_Remove)
                    .addComponent(btn_Update)
                    .addComponent(btnReset))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed

        boolean check = validator();
        if (check == true){
            int option = JOptionPane.showConfirmDialog(null,"Do you really want to Update");

            if(option==0)
            {
                String CusID = lbl_ID.getText();
                String name = txt_Name.getText();
                String address = txt_Address.getText();
                String email = txt_Email.getText();
                String tp = txt_TP.getText();
                String nic = txtNic.getText();

                try
                {
                    String sql = "UPDATE customer SET name ='"+ name +"', nic = '"+ nic +"' , address = '"+ address +"', email='"+ email +"', telephone='"+ tp +"' where customerID ='"+ CusID +"' ";
                    pst = con.prepareStatement(sql);
                    pst.execute();

                    tableload();
                    reset();
                    System.out.println("U");
                }
                catch(Exception e)
                {
                    System.out.println(e);
                    System.out.println("Update");
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbl_cusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cusMouseClicked

        btn_Update.setEnabled(true);
        btn_Remove.setEnabled(true);
        btn_Save.setEnabled(false);
        
        // TODO add your handling code here:
        int r = tbl_cus.getSelectedRow();
        String CusID = tbl_cus.getValueAt(r, 0).toString();
        String name = tbl_cus.getValueAt(r, 1).toString();
        String nic = tbl_cus.getValueAt(r, 2).toString();
        String address = tbl_cus.getValueAt(r, 3).toString();
        String email = tbl_cus.getValueAt(r, 4).toString();
        String tp = tbl_cus.getValueAt(r, 5).toString();

        txt_Name.setText(name);
        txtNic.setText(nic);
        txt_Address.setText(address);
        txt_Email.setText(email);
        txt_TP.setText(tp);

        lbl_ID.setText("CUS"+CusID);
    }//GEN-LAST:event_tbl_cusMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        String name = txt_search.getText();

        String sql = "SELECT customerID,name,nic,address,email,telephone from customer WHERE name LIKE '%"+name+"%'";

        try
        {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tbl_cus.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed

        int x = JOptionPane.showConfirmDialog(null,"Do you really want to Delete this?");
        String name = txt_Name.getText();
        if (name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please select a raw to delete!");
        }
        else
        {
            if( x == 0)
            {
                try
                {
                    String CusID = lbl_ID.getText();
                    String sql = "DELETE from customer where customerID ='"+ CusID +"'";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    
                    tableload();
                    reset();
                    
                }
                catch(Exception e)
                {
                    System.out.println(e);
                   System.out.println("Delete");
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        boolean check = validator();

        if (check == true){
            String name = txt_Name.getText();
            String address = txt_Address.getText();
            String email = txt_Email.getText();
            String tp = txt_TP.getText();
            String nic = txtNic.getText();
            

            try
            {
                String q = "INSERT INTO customer(name,address,email,telephone,nic) values ('"+ name +"','"+ address +"','"+ email +"','"+tp+"', '"+ nic +"')";
                pst = con.prepareStatement(q);
                pst.execute();

                tableload();
                reset();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainCustomers x = new mainCustomers();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_TPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TPKeyReleased
        // TODO add your handling code here:
        String faccos =txt_TP.getText();
         
        for(int i =0; i<faccos.length(); i++){
        
        char c = faccos.charAt(i);
        
        if(Character.isDigit(c))
        {
            
        }
        else if(Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(null, "This field cannot have letters", "Error",0);
            txt_TP.setText(" ");
 
            break;
        }
        }
        
    }//GEN-LAST:event_txt_TPKeyReleased

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_TP;
    private javax.swing.JLabel lbl_cusNo;
    private javax.swing.JLabel lbl_cusRegistration;
    private javax.swing.JLabel lbl_searchNmae;
    private javax.swing.JTable tbl_cus;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextArea txt_Address;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_TP;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
