/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface_Cushioning.mainCushioning;
import Interface_Delivery.mainDelivery;
import Interface_Employee.mainEmployees;
import Interface_Finance.mainFinance;
import Interface_Return.mainRepair;
import Interface_Sales.mainCustomers;
import Interface_Stock.mainStock;
import Interface_Suppliers.mainSuppliers;
import javax.swing.UIManager;


public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFunction1 = new javax.swing.JButton();
        btnFunction2 = new javax.swing.JButton();
        btnFunction3 = new javax.swing.JButton();
        btnFunction4 = new javax.swing.JButton();
        btnFunction5 = new javax.swing.JButton();
        btnFunction6 = new javax.swing.JButton();
        btnFunction7 = new javax.swing.JButton();
        btnFunction8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ABC Furniture");

        btnFunction1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction1.setText("Materials, Orders and Suppliers");
        btnFunction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction1ActionPerformed(evt);
            }
        });

        btnFunction2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction2.setText("Customers & Sales");
        btnFunction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction2ActionPerformed(evt);
            }
        });

        btnFunction3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction3.setText("Furniutre return");
        btnFunction3.setMaximumSize(new java.awt.Dimension(279, 31));
        btnFunction3.setMinimumSize(new java.awt.Dimension(279, 31));
        btnFunction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction3ActionPerformed(evt);
            }
        });

        btnFunction4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction4.setText("Furniture and material stock");
        btnFunction4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction4ActionPerformed(evt);
            }
        });

        btnFunction5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction5.setText("Delivery");
        btnFunction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction5ActionPerformed(evt);
            }
        });

        btnFunction6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction6.setText("Finance & Cost");
        btnFunction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction6ActionPerformed(evt);
            }
        });

        btnFunction7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction7.setText("Quotation");
        btnFunction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction7ActionPerformed(evt);
            }
        });

        btnFunction8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFunction8.setText("Employees & Salaries");
        btnFunction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunction8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFunction1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFunction3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFunction4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFunction5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFunction7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFunction6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFunction8, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(btnFunction2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunction2)
                    .addComponent(btnFunction1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFunction3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFunction7))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunction4)
                    .addComponent(btnFunction6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunction5)
                    .addComponent(btnFunction8))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFunction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction1ActionPerformed
        
        mainSuppliers x = new mainSuppliers();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction1ActionPerformed

    private void btnFunction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction2ActionPerformed
        // TODO add your handling code here:
        mainCustomers x = new mainCustomers();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction2ActionPerformed

    private void btnFunction4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction4ActionPerformed
        // TODO add your handling code here:
        mainStock x = new mainStock();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction4ActionPerformed

    private void btnFunction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction5ActionPerformed
        // TODO add your handling code here:
        mainDelivery x = new mainDelivery();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction5ActionPerformed

    private void btnFunction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction6ActionPerformed
        // TODO add your handling code here
        mainFinance x = new mainFinance();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction6ActionPerformed

    private void btnFunction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction7ActionPerformed
        // TODO add your handling code here:

        mainCushioning x = new mainCushioning();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFunction7ActionPerformed

    private void btnFunction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction8ActionPerformed
        // TODO add your handling code here:

        mainEmployees x = new mainEmployees();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFunction8ActionPerformed

    private void btnFunction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunction3ActionPerformed
        // TODO add your handling code here:
        mainRepair x = new mainRepair();
        x.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnFunction3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//              if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                //UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFunction1;
    private javax.swing.JButton btnFunction2;
    private javax.swing.JButton btnFunction3;
    private javax.swing.JButton btnFunction4;
    private javax.swing.JButton btnFunction5;
    private javax.swing.JButton btnFunction6;
    private javax.swing.JButton btnFunction7;
    private javax.swing.JButton btnFunction8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
